### ISSUE TITLE
when i type ,help bot reply but my friend type ,help not reply

### ISSUE THREAD

**Issue by Sqm3t** [purpl3r0se/GrowGamble#3]

**Comment by Sqm3t** [comment]
File "C:\Users\Pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Pc\Desktop\GrowGamble-main\main.py", line 47, in on_message
    item = split[1]
           ~^^^
IndexError: list index out of range

**Comment by purpl3r0se** [comment]
> File "C:\Users\Pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event await coro(*args, **kwargs) File "C:\Users\Pc\Desktop\GrowGamble-main\main.py", line 47, in on_message item = split[1] ~^^^ IndexError: list index out of range

this shouldn't even be ran, the only moment that part is being executed is when the message is being sent by a specific webhook

**Comment by purpl3r0se** [comment]
> > File "C:\Users\Pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event await coro(*args, **kwargs) File "C:\Users\Pc\Desktop\GrowGamble-main\main.py", line 47, in on_message item = split[1] ~^^^ IndexError: list index out of range
> 
> this shouldn't even be ran, the only moment that part is being executed is when the message is being sent by a specific webhook

to add to this, i also never got this error when running it myself

**Comment by Sqm3t** [comment]
ok but my friend cant use bot

**Comment by Sqm3t** [comment]
lw'#8420 add me
